# Generated by Django 2.1.7 on 2019-04-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.CharField(default="<div class='g-body-branch-photo-bgi' style='background: url(/media/defaultPhotos/7.jpg)'></div>", max_length=800),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default='2019-04-18 09:49:35'),
        ),
    ]
