# Generated by Django 2.1.7 on 2019-04-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190418_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.CharField(default="<div class='g-body-branch-photo-bgi' style='background: url(/media/defaultPhotos/9.jpg)'></div>", max_length=800),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default='2019-04-18 15:36:09'),
        ),
    ]
