# Generated by Django 2.1.7 on 2019-04-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190418_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.CharField(default="<div class='g-body-branch-photo-bgi' style='background: url(/media/defaultPhotos/26.jpg)'></div>", max_length=800),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default='2019-04-19 11:30:30'),
        ),
    ]
