# Generated by Django 2.1.7 on 2019-04-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190419_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorArticles', to='oauth.MUL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.CharField(default="<div class='g-body-branch-photo-bgi' style='background: url(/media/defaultPhotos/17.jpg)'></div>", max_length=800),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default='2019-04-19 15:28:27'),
        ),
    ]
