# Generated by Django 2.1.7 on 2019-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MUL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messyId', models.PositiveIntegerField(verbose_name='Messy号')),
                ('is_messy', models.BooleanField(default='0', verbose_name='是否为管理员')),
                ('name', models.CharField(default='MessyCLSa_0408', max_length=100, verbose_name='用户名')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('passwd', models.CharField(max_length=100, verbose_name='密码')),
                ('date_joined', models.CharField(default='2019-04-16 20-04-08', max_length=100, verbose_name='注册时间')),
                ('last_login', models.CharField(default='该用户注册后还没登录过', max_length=100, verbose_name='最后一次登录时间')),
                ('last_login_IP', models.CharField(default='该用户注册后还没登录过', max_length=100, verbose_name='最后一次登录IP')),
            ],
            options={
                'verbose_name': '用户',
                'ordering': ['date_joined'],
            },
        ),
    ]
