# Generated by Django 2.1.7 on 2019-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20190418_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mul',
            name='date_joined',
            field=models.CharField(default='2019-04-18 20-38-21', max_length=100, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='mul',
            name='name',
            field=models.CharField(default='MessyNEhM_3821', max_length=100, verbose_name='用户名'),
        ),
    ]
