# Generated by Django 2.1.7 on 2019-04-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20190418_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mul',
            name='date_joined',
            field=models.CharField(default='2019-04-19 11-30-30', max_length=100, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='mul',
            name='name',
            field=models.CharField(default='MessydmWp_3030', max_length=100, verbose_name='用户名'),
        ),
    ]
