# Generated by Django 2.1.7 on 2019-04-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_auto_20190419_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mul',
            name='date_joined',
            field=models.CharField(default='2019-04-22 15-28-50', max_length=100, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='mul',
            name='name',
            field=models.CharField(default='MessyujZz_2850', max_length=100, verbose_name='用户名'),
        ),
    ]
