# Generated by Django 2.1.7 on 2019-04-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='searchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='搜索次数')),
                ('keyword', models.CharField(max_length=100, verbose_name='搜索关键词')),
            ],
            options={
                'verbose_name': '搜索热词',
                'ordering': ['-count'],
            },
        ),
    ]
