# Generated by Django 2.1.7 on 2019-04-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='未知错误，记录默认时间2019-04-18 09:03:03', max_length=100)),
                ('count', models.IntegerField(default=0, verbose_name='网站访问次数')),
                ('crawlerCount', models.IntegerField(default=0, verbose_name='爬虫访问次数')),
            ],
            options={
                'verbose_name': '网站单日访问量统计',
                'verbose_name_plural': '网站单日访问量统计',
            },
        ),
        migrations.CreateModel(
            name='goodBoyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default='2019-04-18 09:03:03', verbose_name='时间')),
                ('name', models.CharField(max_length=100, verbose_name='昵称')),
                ('note', models.CharField(max_length=500, verbose_name='备注')),
                ('money', models.IntegerField(verbose_name='赞赏金额')),
            ],
            options={
                'verbose_name': '赞赏列表',
                'verbose_name_plural': '赞赏列表',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='OperatingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default='2019-04-18 09:03:03')),
                ('user', models.CharField(max_length=100, verbose_name='默认用户')),
                ('operating', models.CharField(max_length=500, verbose_name='默认操作')),
                ('operatingIP', models.CharField(max_length=500, verbose_name='默认IP')),
            ],
            options={
                'verbose_name': '历史操作',
                'verbose_name_plural': '历史操作',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default='2019-04-18 09:03:03')),
                ('ip', models.CharField(max_length=30, verbose_name='IP地址')),
                ('ip_address', models.CharField(default='等待查询中...', max_length=200, verbose_name='IP地址归属地')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('url', models.CharField(max_length=100)),
                ('shebei_meg', models.CharField(max_length=800)),
            ],
            options={
                'verbose_name': '访问用户信息',
                'verbose_name_plural': '访问用户信息',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='网站访问总次数')),
                ('crawlerCount', models.IntegerField(default=0, verbose_name='爬虫访问总次数')),
            ],
            options={
                'verbose_name': '网站访问总次数',
                'verbose_name_plural': '网站访问总次数',
            },
        ),
    ]
