# Generated by Django 2.1.7 on 2019-04-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20190419_1528'),
        ('manager', '0004_auto_20190419_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgS', models.CharField(max_length=100, verbose_name='小缩略图url')),
                ('imgD', models.CharField(max_length=100, verbose_name='中缩略图url')),
                ('imgB', models.CharField(max_length=100, verbose_name='原图url')),
                ('time', models.DateTimeField(default='2019-04-19 15:28:27', verbose_name='图片上传时间')),
                ('describe', models.CharField(max_length=1000, verbose_name='图片描述')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorCamera', to='oauth.MUL', verbose_name='图片作者名')),
            ],
            options={
                'verbose_name': '摄影图片列表',
                'verbose_name_plural': '摄影图片列表',
                'ordering': ['-time'],
            },
        ),
        migrations.AlterField(
            model_name='daynumber',
            name='day',
            field=models.CharField(default='未知错误，记录默认时间2019-04-19 15:28:27', max_length=100),
        ),
        migrations.AlterField(
            model_name='goodboylist',
            name='time',
            field=models.DateTimeField(default='2019-04-19 15:28:27', verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='operatinghistory',
            name='time',
            field=models.DateTimeField(default='2019-04-19 15:28:27'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='time',
            field=models.DateTimeField(default='2019-04-19 15:28:27'),
        ),
    ]
