# Generated by Django 2.1.7 on 2019-04-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20190419_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='imgD',
            new_name='imgM',
        ),
        migrations.AlterField(
            model_name='daynumber',
            name='day',
            field=models.CharField(default='未知错误，记录默认时间2019-04-19 16:53:15', max_length=100),
        ),
        migrations.AlterField(
            model_name='goodboylist',
            name='time',
            field=models.DateTimeField(default='2019-04-19 16:53:15', verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='operatinghistory',
            name='time',
            field=models.DateTimeField(default='2019-04-19 16:53:15'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='time',
            field=models.DateTimeField(default='2019-04-19 16:53:15', verbose_name='图片上传时间'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='time',
            field=models.DateTimeField(default='2019-04-19 16:53:15'),
        ),
    ]
